spring:
  application:
    name: VideoUpload
server:
  port: 8083
  address: 0.0.0.0

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_ENDPOINT}/eureka/

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
