name: Run tests on Java 21

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests on Java 21
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
      - run: ./mvnw -f pom.xml test
